packaging_format = 2

id = "wekan"
name = "Wekan"
description.en = "Trello-like kanban"
description.fr = "Kanban similaire à Trello"

version = "8.70~ynh1"

maintainers = [ ]

[upstream]
license = "MIT"
website = "https://wekan.github.io"
demo = "https://demo.sandstorm.io/appdemo/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h"
admindoc = "https://github.com/wekan/wekan/wiki"
code = "https://github.com/wekan/wekan"

[integration]
yunohost = ">= 12.1.38"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wekan"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

        [resources.sources.main]
        amd64.url = "https://github.com/wekan/wekan/releases/download/v8.70/wekan-8.70-amd64.zip"
        amd64.sha256 = "444b8e0b9672e0dd54693e66c470a0d6b159d6806441855dd79c201a04dca622"
        arm64.url = "https://github.com/wekan/wekan/releases/download/v8.70/wekan-8.70-arm64.zip"
        arm64.sha256 = "c77781c4a90d82b570cab0e1ba4611d0a112645efda929a7750ba8a35c2945a2"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = ".*-amd64.zip"
        autoupdate.asset.arm64 = ".*-arm64.zip"

    [resources.ports]

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    admin.allowed = "admins"
