packaging_format = 2

id = "wekan"
name = "Wekan"
description.en = "Trello-like kanban"
description.fr = "Kanban similaire à Trello"

version = "11.28~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://wekan.github.io"
demo = "https://demo.sandstorm.io/appdemo/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h"
admindoc = "https://github.com/wekan/wekan/wiki"
code = "https://github.com/wekan/wekan"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wekan"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

        [resources.sources.main]
        amd64.url = "https://github.com/wekan/wekan/releases/download/v11.28/wekan-11.28-amd64.zip"
        amd64.sha256 = "7a33fc3c17cc65d8173c21e43705542ad6f87814207b641c6e4bf9d25592c028"
        arm64.url = "https://github.com/wekan/wekan/releases/download/v11.28/wekan-11.28-arm64.zip"
        arm64.sha256 = "0d2310f861455754e02f39f3b27c75c4ee53d9e55da29e8aab69aa4cb3ae725d"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "wekan-\\d+\\.\\d+-amd64.zip$"
        autoupdate.asset.arm64 = "wekan-\\d+\\.\\d+-arm64.zip$"

    [resources.ports]

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    admin.allowed = "admins"

    [resources.nodejs]
    version = "24"
