packaging_format = 2

id = "wekan"
name = "Wekan"
description.en = "Trello-like kanban"
description.fr = "Kanban similaire à Trello"

version = "9.47~ynh1"

maintainers = [ ]

[upstream]
license = "MIT"
website = "https://wekan.github.io"
demo = "https://demo.sandstorm.io/appdemo/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h"
admindoc = "https://github.com/wekan/wekan/wiki"
code = "https://github.com/wekan/wekan"

[integration]
yunohost = ">= 12.1.38"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wekan"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

        [resources.sources.main]
        amd64.url = "https://github.com/wekan/wekan/releases/download/v9.47/wekan-9.47-amd64.zip"
        amd64.sha256 = "a8d188743c014e3e0b9cfbc7926f82295e3f0075e38115993cb41cc76265c69c"
        arm64.url = "https://github.com/wekan/wekan/releases/download/v9.47/wekan-9.47-arm64.zip"
        arm64.sha256 = "26d719a12b24bd1e243bd71af41384af9a41f48da16143fc8d76565da464d247"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = ".*-amd64.zip"
        autoupdate.asset.arm64 = "wekan-\\d+\\.\\d+-arm64.zip"

    [resources.ports]

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    admin.allowed = "admins"
