#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _future.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path)
is_public=$(ynh_app_setting_get $app is_public)
final_path=$(ynh_app_setting_get $app final_path)
port=$(ynh_app_setting_get $app port)

#=================================================
# Check version
#=================================================
abort_if_up_to_date

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

ynh_backup_before_upgrade	# Backup the current version of the app
ynh_clean_setup () {
	ynh_restore_upgradebackup	# restore it if the upgrade fails
}
ynh_abort_if_errors	# Exit if an error occurs during the execution of the script

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

if ynh_version_gt "0.45-2" "${version}" ; then
    ynh_replace_string "Environment=ROOT_URL=http://127.0.0.1:$port$path_url" "Environment=ROOT_URL=https://$domain$path_url/" "/etc/systemd/system/$app.service"
    systemctl daemon-reload
fi
if ynh_version_gt "0.45-3" "${version}" ; then
    yunohost service add $app
fi
if ynh_version_gt "0.54-2" "${version}" ; then
    systemctl enable mongod
    systemctl restart mongod
fi
if ynh_version_gt "0.54-3" "${version}" ; then
    apt-key del EA312927
    wget https://www.mongodb.org/static/pgp/server-3.2.asc -O - | apt-key add -
fi
if ynh_version_gt "0.63-1" "${version}" ; then
    ynh_install_nodejs 4.8.7
fi
if ynh_version_gt "0.77-2" "${version}" ; then
    ynh_install_nodejs 8.9.3
    # Create a dedicated systemd config
    ynh_replace_string "__NODEJS__"   "$nodejs_use_version" "../conf/systemd.service"
    ynh_replace_string "__ENV_PATH__" "$PATH"               "../conf/systemd.service"
    ynh_replace_string "__DB_NAME__"  "$app"                "../conf/systemd.service"
    ynh_replace_string "__URI__"      "$path_url/"          "../conf/systemd.service"
    ynh_replace_string "__PORT__"     "$port"               "../conf/systemd.service"
    ynh_replace_string "__DOMAIN__"   "$domain"             "../conf/systemd.service"
    ynh_add_systemd_config
fi


#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# Download, check integrity, uncompress and patch the source from app.src
# For this app sources are in app subdirectory 
ynh_setup_source "$final_path"

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set strong right permissions to app files
chown -R $app: "$final_path"
chmod -R 640 "$final_path"
find "$final_path" -type d -print0 | xargs -0 chmod 750

# Relaunch a npm install
pushd $final_path/programs/server
ynh_use_nodejs
npm install
popd

#=================================================
# RELOAD NGINX
#=================================================
systemctl restart $app
systemctl reload nginx
